### ISSUE TITLE
Tagless enum redeclared

### ISSUE THREAD

**Issue by millerlogic** [facebookresearch/CParser#1]
I'm using CParser to do some source code transformations. I ran into an issue with code like the following:

``` c
typedef enum { A, B } One, Two;
```

What happens is that because the enum has no tag name, One and Two get fully redeclared like the following:

``` c
typedef enum{A,B}One;
typedef enum{A,B}Two;
```

so the names A and B have a collision and it breaks the source.

I worked around this in parseEnum by generating a dummy tag name when a name isn't present, but I suspect there may be a better solution. The same issue may happen with struct and union, but the fix might not be that simple when considering anonymous structs.

**Comment by leonbottou** [comment]
If the problem is name collision, it may be enough to ensure that enum constants redeclared with the same values are not collisions.  Would that be enough of a fix?

**Comment by leonbottou** [comment]
Correction. Only the second excerpt (two typedefs) gives you a name collision in cparser (as well as in gcc and clang).  On the other hand, A single typedef with two names gives:

```
+--------------------------
| Definition{init={..},sclass="[enum]",where="tst.c:2",type=Qualified{_enum={..},const=true,t=Type{n="int"}},name="A",intval=1}
| [enum] const int A = 1
+--------------------------
| Definition{init={..},sclass="[enum]",where="tst.c:2",type=Qualified{_enum={..},const=true,t=Type{n="int"}},name="B",intval=2}
| [enum] const int B = 2
+--------------------------
| TypeDef{sclass="typedef",where="tst.c:2",type=Enum{Pair{"A"},Pair{"B"}},name="One"}
| typedef enum{A,B}One
+--------------------------
| TypeDef{sclass="typedef",where="tst.c:2",type=Enum{Pair{"A"},Pair{"B"}},name="Two"}
| typedef enum{A,B}Two
+--------------------------
```

which is correct in terms of parsing.

I guess that what happens is that you generate code based on this information and repeat the enum declaration, which causes a name collision when you run the c compiler on the generated code.  One way to deal with this would be remark that the two <type=> in the tagged tables refer to the same type. So if you set a field name <tag=xxxx> in the first enum when you see it, the tag will also appear in the second enum, and you'll know it is the same.

On the one hand, the lcdecl output is correct because this is what the parsed code says (One and Two are defined to be the same anonymous enum type, not defined to be a same tagged enum type). On the other hand, I can see that this forces some clumsiness when generating code.   

Maybe an option to invent tags for all anonymous types would help?

**Comment by millerlogic** [comment]
> One and Two are defined to be the same anonymous enum type, not defined to be a same tagged enum type

While I think I see what you mean, I can't say that I see the distinction.

The fact that these experiments compile gives me the impression that they're the same type:

``` c
struct { int i; } s1, s2;
typedef struct { int j; } T1, *PT1;
enum { X } e1, e2;
typedef enum { Y } T2, *PT2;
int main() {
  T1 t1;
  PT1 pt1 = &t1;
  T2 t2;
  PT2 pt2 = &t2;
  s1 = s2;
  e1 = e2;
  return 0;
}
```

Either way the option you suggested would work.

There's one scenario that might break with the option, which might not even be valid C but is used in some cases:

``` c
struct X
{
  union { int i; char c; };
}
```

I'm not an expert on the standards, so I'll go with what you decide. Thanks for taking a look :)

**Comment by leonbottou** [comment]
But observe:

```
  struct {int a;} x;
  struct {int a;} y;
  void foo() { x = y;}
```

gives a type mismatch error, whereas

```
 struct {int a;} x,y;
 void foo() {x=y;}
```

doesn't.

In the cparser output, the difference between these two cases is that the type objects, in the first case, are two tables with identical contents, in the second case, are the same table.  But one could try to make this clearer...

**Comment by leonbottou** [comment]
Added option -Ztag to program lcdecl. This option causes lcdecl to treat all structs, unions, and enums as tagged types, possibly using synthetic tags of the form __anon_XXXXX. It is assumed that such names are not used anywhere in the parsed program. This is useful for certain code transformation applications.

**Comment by leonbottou** [comment]
Note that gcc doesn't like this either.
```bash
$ echo > xx.c <<EOF
typedef enum{A,B}One;
typedef enum{A,B}Two;
EOF
$ gcc -c xx.c
xx.c:2:14: error: redefinition of enumerator 'A'
typedef enum{A,B}Two;
             ^
xx.c:1:14: note: previous definition is here
typedef enum{A,B}One;
             ^
xx.c:2:16: error: redefinition of enumerator 'B'
typedef enum{A,B}Two;
               ^
xx.c:1:16: note: previous definition is here
typedef enum{A,B}One;
               ^
2 errors generated.
```
